### ISSUE TITLE
Paillier::keypair().keys()  is extremely slow

### ISSUE THREAD

**Issue by hustxiaoc** [ZenGo-X/emerald-city#13]
It takes a long time to get the result when calling `Paillier::keypair().keys()`

**Comment by hustxiaoc** [comment]
As you can see the test case.
![image](https://user-images.githubusercontent.com/1102038/66815774-71b90200-ef6b-11e9-8448-8977d5843e66.png)

**Comment by vhnatyk** [comment]
@hustxiaoc pls try `--release` with `cargo test`, I guess it can be closed now
